# full config example. Refer to bbconf/const.py for key names and default values

path:
  pipelines_output: $HOME/results_pipeline

database:
  host: localhost
  bed_index: bed_index
  bedset_index: bedset_index

server:
  host: 0.0.0.0
  port: 8000