# full config example. Refer to bbconf/const.py for key names and default values

path:
  pipelines_output: $HOME/results_pipeline

database:
  name: postgres
  user: postgres
  password: postgres
  host: localhost
  bed_table: bedfiles
  bedset_table: bedsets

server:
  host: 0.0.0.0
  port: 8000