"""Initial migration

Revision ID: 20310bfee23a
Revises: 
Create Date: 2024-12-16 15:33:36.517295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20310bfee23a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bedsets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Name of the bedset'),
    sa.Column('description', sa.String(), nullable=True, comment='Description of the bedset'),
    sa.Column('submission_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_update_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('md5sum', sa.String(), nullable=True, comment='MD5 sum of the bedset'),
    sa.Column('bedset_means', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Mean values of the bedset'),
    sa.Column('bedset_standard_deviation', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Median values of the bedset'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bedsets_id'), 'bedsets', ['id'], unique=False)
    op.create_table('geo_gse_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gse', sa.String(), nullable=False, comment='GSE number'),
    sa.Column('status', sa.String(), nullable=False, comment='Status of the GEO project'),
    sa.Column('submission_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('number_of_files', sa.Integer(), nullable=False, comment='Number of files'),
    sa.Column('number_of_success', sa.Integer(), nullable=False, comment='Number of success'),
    sa.Column('number_of_skips', sa.Integer(), nullable=False, comment='Number of skips'),
    sa.Column('number_of_fails', sa.Integer(), nullable=False, comment='Number of fails'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gse')
    )
    op.create_index(op.f('ix_geo_gse_status_id'), 'geo_gse_status', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shorthand', sa.String(), nullable=True, comment='License shorthand'),
    sa.Column('label', sa.String(), nullable=False, comment='License label'),
    sa.Column('description', sa.String(), nullable=False, comment='License description'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_table('bed',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genome_alias', sa.String(), nullable=True),
    sa.Column('genome_digest', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('bed_format', sa.String(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False, comment='Whether sample was added to qdrant'),
    sa.Column('pephub', sa.Boolean(), nullable=False, comment='Whether sample was added to pephub'),
    sa.Column('submission_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_update_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_universe', sa.Boolean(), nullable=True),
    sa.Column('license_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_id'), 'bed', ['id'], unique=False)
    op.create_index(op.f('ix_bed_license_id'), 'bed', ['license_id'], unique=False)
    op.create_table('geo_gsm_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gse_status_id', sa.Integer(), nullable=False),
    sa.Column('gsm', sa.String(), nullable=False, comment='GSM number'),
    sa.Column('sample_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, comment='Status of the GEO sample'),
    sa.Column('error', sa.String(), nullable=True, comment='Error message'),
    sa.Column('genome', sa.String(), nullable=True, comment='Genome'),
    sa.ForeignKeyConstraint(['gse_status_id'], ['geo_gse_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_gsm_status_gse_status_id'), 'geo_gsm_status', ['gse_status_id'], unique=False)
    op.create_index(op.f('ix_geo_gsm_status_id'), 'geo_gsm_status', ['id'], unique=False)
    op.create_table('bed_metadata',
    sa.Column('species_name', sa.String(), nullable=False, comment='Organism name'),
    sa.Column('species_id', sa.String(), nullable=True, comment='Organism taxon id'),
    sa.Column('genotype', sa.String(), nullable=True, comment='Genotype of the sample'),
    sa.Column('phenotype', sa.String(), nullable=True, comment='Phenotype of the sample'),
    sa.Column('cell_type', sa.String(), nullable=True, comment='Specific kind of cell with distinct characteristics found in an organism. e.g. Neurons, Hepatocytes, Adipocytes'),
    sa.Column('cell_line', sa.String(), nullable=True, comment='Population of cells derived from a single cell and cultured in the lab for extended use, e.g. HeLa, HepG2, k562'),
    sa.Column('tissue', sa.String(), nullable=True, comment='Tissue type'),
    sa.Column('library_source', sa.String(), nullable=True, comment='Library source (e.g. genomic, transcriptomic)'),
    sa.Column('assay', sa.String(), nullable=True, comment='Experimental protocol (e.g. ChIP-seq)'),
    sa.Column('antibody', sa.String(), nullable=True, comment='Antibody used in the assay'),
    sa.Column('target', sa.String(), nullable=True, comment='Target of the assay (e.g. H3K4me3)'),
    sa.Column('treatment', sa.String(), nullable=True, comment='Treatment of the sample (e.g. drug treatment)'),
    sa.Column('global_sample_id', sa.String(), nullable=True, comment='Global sample identifier. e.g. GSM000'),
    sa.Column('global_experiment_id', sa.String(), nullable=True, comment='Global experiment identifier. e.g. GSE000'),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_metadata_id'), 'bed_metadata', ['id'], unique=False)
    op.create_table('bed_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number_of_regions', sa.Float(), nullable=True),
    sa.Column('gc_content', sa.Float(), nullable=True),
    sa.Column('median_tss_dist', sa.Float(), nullable=True),
    sa.Column('mean_region_width', sa.Float(), nullable=True),
    sa.Column('exon_frequency', sa.Float(), nullable=True),
    sa.Column('intron_frequency', sa.Float(), nullable=True),
    sa.Column('promoterprox_frequency', sa.Float(), nullable=True),
    sa.Column('intergenic_frequency', sa.Float(), nullable=True),
    sa.Column('promotercore_frequency', sa.Float(), nullable=True),
    sa.Column('fiveutr_frequency', sa.Float(), nullable=True),
    sa.Column('threeutr_frequency', sa.Float(), nullable=True),
    sa.Column('fiveutr_percentage', sa.Float(), nullable=True),
    sa.Column('threeutr_percentage', sa.Float(), nullable=True),
    sa.Column('promoterprox_percentage', sa.Float(), nullable=True),
    sa.Column('exon_percentage', sa.Float(), nullable=True),
    sa.Column('intron_percentage', sa.Float(), nullable=True),
    sa.Column('intergenic_percentage', sa.Float(), nullable=True),
    sa.Column('promotercore_percentage', sa.Float(), nullable=True),
    sa.Column('tssdist', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_stats_id'), 'bed_stats', ['id'], unique=False)
    op.create_table('bedfile_bedset_relation',
    sa.Column('bedset_id', sa.String(), nullable=False),
    sa.Column('bedfile_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bedfile_id'], ['bed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bedset_id'], ['bedsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bedset_id', 'bedfile_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Name of the file, e.g. bed, bigBed'),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False, comment='Type of the object, e.g. file, plot, ...'),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('path_thumbnail', sa.String(), nullable=True, comment='Thumbnail path of the file'),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True, comment='Size of the file'),
    sa.Column('bedfile_id', sa.String(), nullable=True),
    sa.Column('bedset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bedfile_id'], ['bed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bedset_id'], ['bedsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_bedfile_id'), 'files', ['bedfile_id'], unique=False)
    op.create_index(op.f('ix_files_bedset_id'), 'files', ['bedset_id'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('genome_ref_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('provided_genome', sa.String(), nullable=False),
    sa.Column('compared_genome', sa.String(), nullable=False, comment='Compared Genome'),
    sa.Column('xs', sa.Float(), nullable=True),
    sa.Column('oobr', sa.Float(), nullable=True),
    sa.Column('sequence_fit', sa.Float(), nullable=True),
    sa.Column('assigned_points', sa.Integer(), nullable=False),
    sa.Column('tier_ranking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_id', 'compared_genome')
    )
    op.create_index(op.f('ix_genome_ref_stats_bed_id'), 'genome_ref_stats', ['bed_id'], unique=False)
    op.create_index(op.f('ix_genome_ref_stats_id'), 'genome_ref_stats', ['id'], unique=False)
    op.create_table('universes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True, comment='Method used to create the universe'),
    sa.Column('bedset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bedset_id'], ['bedsets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['bed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universes_bedset_id'), 'universes', ['bedset_id'], unique=False)
    op.create_index(op.f('ix_universes_id'), 'universes', ['id'], unique=False)
    op.create_table('tokenized_bed',
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('universe_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False, comment='Path to the tokenized bed file'),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bed_id', 'universe_id')
    )
    op.create_index(op.f('ix_tokenized_bed_bed_id'), 'tokenized_bed', ['bed_id'], unique=False)
    op.create_index(op.f('ix_tokenized_bed_universe_id'), 'tokenized_bed', ['universe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenized_bed_universe_id'), table_name='tokenized_bed')
    op.drop_index(op.f('ix_tokenized_bed_bed_id'), table_name='tokenized_bed')
    op.drop_table('tokenized_bed')
    op.drop_index(op.f('ix_universes_id'), table_name='universes')
    op.drop_index(op.f('ix_universes_bedset_id'), table_name='universes')
    op.drop_table('universes')
    op.drop_index(op.f('ix_genome_ref_stats_id'), table_name='genome_ref_stats')
    op.drop_index(op.f('ix_genome_ref_stats_bed_id'), table_name='genome_ref_stats')
    op.drop_table('genome_ref_stats')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_bedset_id'), table_name='files')
    op.drop_index(op.f('ix_files_bedfile_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('bedfile_bedset_relation')
    op.drop_index(op.f('ix_bed_stats_id'), table_name='bed_stats')
    op.drop_table('bed_stats')
    op.drop_index(op.f('ix_bed_metadata_id'), table_name='bed_metadata')
    op.drop_table('bed_metadata')
    op.drop_index(op.f('ix_geo_gsm_status_id'), table_name='geo_gsm_status')
    op.drop_index(op.f('ix_geo_gsm_status_gse_status_id'), table_name='geo_gsm_status')
    op.drop_table('geo_gsm_status')
    op.drop_index(op.f('ix_bed_license_id'), table_name='bed')
    op.drop_index(op.f('ix_bed_id'), table_name='bed')
    op.drop_table('bed')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_geo_gse_status_id'), table_name='geo_gse_status')
    op.drop_table('geo_gse_status')
    op.drop_index(op.f('ix_bedsets_id'), table_name='bedsets')
    op.drop_table('bedsets')
    # ### end Alembic commands ###
