"""Test revision

Revision ID: 6a7dd9655e79
Revises: 20310bfee23a
Create Date: 2024-12-16 16:03:47.710712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7dd9655e79'
down_revision: Union[str, None] = '20310bfee23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bed', 'processed')
    op.drop_column('bedsets', 'author')
    op.drop_column('bedsets', 'processed')
    op.drop_column('bedsets', 'source')
    op.drop_constraint('files_name_bedfile_id_key', 'files', type_='unique')
    op.drop_constraint('files_name_bedset_id_key', 'files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('files_name_bedset_id_key', 'files', ['name', 'bedset_id'])
    op.create_unique_constraint('files_name_bedfile_id_key', 'files', ['name', 'bedfile_id'])
    op.add_column('bedsets', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Source of the bedset'))
    op.add_column('bedsets', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the bedset was processed'))
    op.add_column('bedsets', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Author of the bedset'))
    op.add_column('bed', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the bed file was processed'))
    # ### end Alembic commands ###
