DEFAULT_DB_NAME = "bedbase"
DEFAULT_DB_PORT = 5432
DEFAULT_DB_DIALECT = "postgresql"
DEFAULT_DB_DRIVER = "psycopg"

DEFAULT_QDRANT_HOST = "localhost"
DEFAULT_QDRANT_PORT = 6333
DEFAULT_QDRANT_FILE_COLLECTION_NAME = "bedbase"
DEFAULT_QDRANT_BIVEC_COLLECTION_NAME = "bed_text"
DEFAULT_QDRANT_HYBRID_COLLECTION_NAME = "bedbase_query_search"
DEFAULT_QDRANT_API_KEY = None

DEFAULT_SERVER_PORT = 80
DEFAULT_SERVER_HOST = "0.0.0.0"

DEFAULT_TEXT2VEC_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_SPARSE_MODEL = "prithivida/Splade_PP_en_v2"
DEFAULT_REGION2_VEC_MODEL = "databio/r2v_encoder-ChIP-atlas-hg38"

DEFAULT_PEPHUB_NAMESPACE = "databio"
DEFAULT_PEPHUB_NAME = "bedbase_all"
DEFAULT_PEPHUB_TAG = "default"

DEFAULT_S3_BUCKET = "bedbase"


S3_FILE_PATH_FOLDER = "files"
S3_PLOTS_PATH_FOLDER = "stats"
S3_BEDSET_PATH_FOLDER = "bedsets"

TEXT_EMBEDDING_DIMENSION = 384
