DEFAULT_DB_NAME = "bedbase"
DEFAULT_DB_PORT = 5432
DEFAULT_DB_DIALECT = "postgresql"
DEFAULT_DB_DRIVER = "psycopg"

DEFAULT_QDRANT_HOST = "localhost"
DEFAULT_QDRANT_PORT = 6333
DEFAULT_QDRANT_COLLECTION_NAME = "bedbase"
DEFAULT_QDRANT_API_KEY = None

DEFAULT_SERVER_PORT = 80
DEFAULT_SERVER_HOST = "0.0.0.0"

DEFAULT_TEXT2VEC_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_VEC2VEC_MODEL = "databio/v2v-MiniLM-v2-ATAC-hg38"
DEFAULT_REGION2_VEC_MODEL = "databio/r2v-ChIP-atlas-hg38"

DEFAULT_PEPHUB_NAMESPACE = "databio"
DEFAULT_PEPHUB_NAME = "allbeds"
DEFAULT_PEPHUB_TAG = "bedbase"

DEFAULT_S3_BUCKET = "bedbase"


S3_FILE_PATH_FOLDER = "files"
S3_PLOTS_PATH_FOLDER = "stats"
S3_BEDSET_PATH_FOLDER = "bedsets"
