"""Added genomic distribution json plots

Revision ID: 845d978eac7d
Revises: 8b0b706d0827
Create Date: 2026-08-16 18:02:03.058352

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "845d978eac7d"
down_revision: Union[str, None] = "8b0b706d0827"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_column("bed", "pephub")
    op.add_column(
        "bed_stats",
        sa.Column(
            "distributions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Full distribution arrays from gtars genomicdist (JSONB)",
        ),
    )
    op.add_column(
        "bedsets",
        sa.Column(
            "bedset_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Pre-aggregated distribution statistics from gtars (JSONB)",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bedsets", "bedset_stats")
    op.drop_column("bed_stats", "distributions")
    op.add_column(
        "bed",
        sa.Column(
            "pephub",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Whether sample was added to pephub",
        ),
    )
